In [27]:
#Importing necesary lib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [28]:
#Importing the data in pandas dataframe
#data is availabe in the kaggle website
file = 'C:/Users/Sanjay  Basnet/Desktop/ML/Drug/drug200.csv' 
df_drug = pd.read_csv(file)


In [30]:
#check first five rows of the data sets
df_drug.head(10)

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  drugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  drugY
9   43   M     LOW      NORMAL   19.368  drugY

In [32]:
#check shape of the variables of the data sets
df_drug.shape

(200, 6)

In [33]:
#more information about the variable
df_drug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [35]:
#check the correlation of the data set
df_drug.corr()

Age   Na_to_K
Age      1.000000 -0.063119
Na_to_K -0.063119  1.000000

In [36]:
#check the missing value of the data sets
df_drug.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [37]:
#Categorical vaiables df["Drug"].value_counts()

In [38]:
df_drug["Sex"].value_counts()

M    104
F     96
Name: Sex, dtype: int64

In [39]:
df_drug["BP"].value_counts()

HIGH      77
LOW       64
NORMAL    59
Name: BP, dtype: int64

In [40]:
#determine attributes for the num var
df_drug.describe().T

count       mean        std     min      25%      50%    75%     max
Age      200.0  44.315000  16.544315  15.000  31.0000  45.0000  58.00  74.000
Na_to_K  200.0  16.084485   7.223956   6.269  10.4455  13.9365  19.38  38.247

Age will be categorized into 7 cat

In [43]:
bin_age = [0, 19, 29, 39, 49, 59, 69, 80]
category_age = ['<20s', '20s', '30s', '40s', '50s', '60s', '>60s']
df_drug['Age_binned'] = pd.cut(df_drug['Age'], bins=bin_age)
df_drug = df_drug.drop(['Age'], axis = 1)

In [44]:
bin_NatoK = [0, 9, 19, 29, 50]
category_NatoK = ['<10', '10-20', '20-30', '>30']
df_drug['Na_to_K_binned'] = pd.cut(df_drug['Na_to_K'], bins=bin_NatoK)
df_drug = df_drug.drop(['Na_to_K'], axis = 1)

In [58]:
#splitting the data set
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [55]:
X = df_drug.drop(["Drug"], axis=1)
y = df_drug["Drug"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=99)

In [59]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)


In [60]:
from sklearn.linear_model import LogisticRegression
LRclassifier = LogisticRegression(solver='liblinear', max_iter=5000)
LRclassifier.fit(X_train, y_train)
y_pred = LRclassifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
LRAcc = accuracy_score(y_pred,y_test)
print('Logistic Regression accuracy is: {:.2f}%'.format(LRAcc*100))


              precision    recall  f1-score   support

       drugA       0.88      0.70      0.78        10
       drugB       0.50      0.67      0.57         3
       drugC       0.67      0.50      0.57         4
       drugX       0.82      0.95      0.88        19
       drugY       0.74      0.71      0.72        24

    accuracy                           0.77        60
   macro avg       0.72      0.70      0.70        60
weighted avg       0.77      0.77      0.76        60

[[ 7  1  0  0  2]
 [ 0  2  0  0  1]
 [ 0  0  2  0  2]
 [ 0  0  0 18  1]
 [ 1  1  1  4 17]]
Logistic Regression accuracy is: 76.67%


In [61]:
from sklearn.neighbors import KNeighborsClassifier
KNclassifier = KNeighborsClassifier(n_neighbors=20)
KNclassifier.fit(X_train, y_train)
y_pred = KNclassifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
KNAcc = accuracy_score(y_pred,y_test)
print('K Neighbours accuracy is: {:.2f}%'.format(KNAcc*100))


              precision    recall  f1-score   support

       drugA       0.75      0.30      0.43        10
       drugB       0.67      0.67      0.67         3
       drugC       1.00      0.25      0.40         4
       drugX       0.81      0.68      0.74        19
       drugY       0.53      0.79      0.63        24

    accuracy                           0.63        60
   macro avg       0.75      0.54      0.57        60
weighted avg       0.69      0.63      0.62        60

[[ 3  0  0  0  7]
 [ 0  2  0  0  1]
 [ 0  0  1  0  3]
 [ 0  0  0 13  6]
 [ 1  1  0  3 19]]
K Neighbours accuracy is: 63.33%


C:\Users\Sanjay  Basnet\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [64]:
from sklearn.svm import SVC
SVCclassifier = SVC(kernel='linear', max_iter=251)
SVCclassifier.fit(X_train, y_train)
y_pred = SVCclassifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
SVCAcc = accuracy_score(y_pred,y_test)
print('SVC accuracy is: {:.2f}%'.format(SVCAcc*100))

              precision    recall  f1-score   support

       drugA       0.90      0.90      0.90        10
       drugB       0.60      1.00      0.75         3
       drugC       0.50      0.50      0.50         4
       drugX       0.84      0.84      0.84        19
       drugY       0.77      0.71      0.74        24

    accuracy                           0.78        60
   macro avg       0.72      0.79      0.75        60
weighted avg       0.79      0.78      0.78        60

[[ 9  1  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  2  0  2]
 [ 0  0  0 16  3]
 [ 1  1  2  3 17]]
SVC accuracy is: 78.33%


In [65]:
from sklearn.naive_bayes import CategoricalNB
NBclassifier1 = CategoricalNB()
NBclassifier1.fit(X_train, y_train)
y_pred = NBclassifier1.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
NBAcc1 = accuracy_score(y_pred,y_test)
print('Naive Bayes accuracy is: {:.2f}%'.format(NBAcc1*100))


              precision    recall  f1-score   support

       drugA       0.82      0.90      0.86        10
       drugB       0.60      1.00      0.75         3
       drugC       0.75      0.75      0.75         4
       drugX       0.81      0.89      0.85        19
       drugY       0.84      0.67      0.74        24

    accuracy                           0.80        60
   macro avg       0.76      0.84      0.79        60
weighted avg       0.81      0.80      0.80        60

[[ 9  1  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  3  0  1]
 [ 0  0  0 17  2]
 [ 2  1  1  4 16]]
Naive Bayes accuracy is: 80.00%


In [66]:
from sklearn.tree import DecisionTreeClassifier
DTclassifier = DecisionTreeClassifier(max_leaf_nodes=20)
DTclassifier.fit(X_train, y_train)
y_pred = DTclassifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
DTAcc = accuracy_score(y_pred,y_test)
print('Decision Tree accuracy is: {:.2f}%'.format(DTAcc*100))


              precision    recall  f1-score   support

       drugA       0.90      0.90      0.90        10
       drugB       0.67      0.67      0.67         3
       drugC       0.67      1.00      0.80         4
       drugX       0.82      0.95      0.88        19
       drugY       0.84      0.67      0.74        24

    accuracy                           0.82        60
   macro avg       0.78      0.84      0.80        60
weighted avg       0.82      0.82      0.81        60

[[ 9  0  0  0  1]
 [ 0  2  0  0  1]
 [ 0  0  4  0  0]
 [ 0  0  0 18  1]
 [ 1  1  2  4 16]]
Decision Tree accuracy is: 81.67%


In [67]:
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(max_leaf_nodes=30)
RFclassifier.fit(X_train, y_train)
y_pred = RFclassifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
RFAcc = accuracy_score(y_pred,y_test)
print('Random Forest accuracy is: {:.2f}%'.format(RFAcc*100))

              precision    recall  f1-score   support

       drugA       0.88      0.70      0.78        10
       drugB       0.67      0.67      0.67         3
       drugC       0.80      1.00      0.89         4
       drugX       0.84      0.84      0.84        19
       drugY       0.72      0.75      0.73        24

    accuracy                           0.78        60
   macro avg       0.78      0.79      0.78        60
weighted avg       0.79      0.78      0.78        60

[[ 7  0  0  0  3]
 [ 0  2  0  0  1]
 [ 0  0  4  0  0]
 [ 0  0  0 16  3]
 [ 1  1  1  3 18]]
Random Forest accuracy is: 78.33%


Model comparision


In [75]:
compare = pd.DataFrame(
          {
              'Model': ['Logistic Regression', 'SVC' , 'K Neighbours' , 'Naive Bayes' , 'Decision Tree' , 'Random Forest'],
                        'Accuracy': [LRAcc*100, KNAcc*100, SVCAcc*100, NBAcc1*100, DTAcc*100 , RFAcc*100 ]})
#compare.sort_values(by='Accuracy', ascending=False)

In [76]:
compare.sort_values(by='Accuracy', ascending=False)

Model   Accuracy
4        Decision Tree  81.666667
3          Naive Bayes  80.000000
2         K Neighbours  78.333333
5        Random Forest  78.333333
0  Logistic Regression  76.666667
1                  SVC  63.333333